### ISSUE TITLE
A Question

### ISSUE THREAD

**Issue by francqz31** [r9y9/nnsvs#180]
Hello, I was just wondering if you can inform me how I can create the music score for my custom English dataset about 5-6 hours ,and if it is manual work or is there a tool or python code to automate it (the music score thing) . My dataset is already transcribed , I academically know that the music score consists of ,input text, input note, input duration , I'm asking about how can I create the input note and duration? because i want to train and i want to make my English dataset formatted like opencpop. here is an example of a single line of train.txt of opencpop:
"2002000043|疯狂|f eng k uang SP|D#4/Eb4 D#4/Eb4 D4 D4 rest|0.609200 0.609200 2.137240 2.137240 3.058880|0.16178 0.44742 0.11219 2.02505 3.05888|0 0 0 0 0"

and also whether or not I'm going to need to do the "|f eng k uang SP" English phoneme translation between the input text  |疯狂| and input note "D#4/Eb4 D#4/Eb4 D4 D4 rest" since my dataset is already in English

If you can answer this that would be so amazing because I'm lost , Thanks in advance.

**Comment by r9y9** [comment]
Please check opencpop's paper https://arxiv.org/abs/2201.07429. In section 2, the details of labeling process is described. You can refer to their method to prepare opencpop-like musical score representation. Basically, manual work is needed.
