### ISSUE TITLE
Recipes for new voices

### ISSUE THREAD

**Issue by r9y9** [r9y9/nnsvs#24]
- [x] 御丹宮くるみさん (female) http://onikuru.info/db-download/
- [x] 夏目悠李さん (male)  https://amanokei.hatenablog.com/entry/2020/04/30/225933
- [x] ofuton_p_utagoe_db https://sites.google.com/view/oftn-utagoedb/%E3%83%9B%E3%83%BC%E3%83%A0

**Comment by r9y9** [comment]
@taroushirani I'd be happy to accept PR(s) if you have them already.

**Comment by taroushirani** [comment]
https://github.com/r9y9/nnsvs/pull/30
