### ISSUE TITLE
Can't advance DTW alignment run script error from singing voice DB　

### ISSUE THREAD

**Issue by usasho** [r9y9/nnsvs#3]
sh run.sh
musicxml/01.xml
Traceback (most recent call last):
  File "gen_lab.py", line 24, in <module>
    lab.append(l.split(), strict=False)
TypeError: append() got an unexpected keyword argument 'strict'
Traceback (most recent call last):
  File "perf_segmentation.py", line 84, in <module>
    np.min(flatten_lengths), np.max(flatten_lengths), np.mean(flatten_lengths)))
  File "<__array_function__ internals>", line 6, in amin
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 2793, in amin
    keepdims=keepdims, initial=initial, where=where)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 90, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity
Prepare data for time-lag models
  0%|                                                     | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "finalize_lab.py", line 49, in <module>
    lab_align = trim_sil_and_pau(hts.load(lab_align_path))
  File "/usr/local/lib/python3.6/dist-packages/nnmnkwii/io/hts.py", line 302, in load
    return labels.load(path, lines)
  File "/usr/local/lib/python3.6/dist-packages/nnmnkwii/io/hts.py", line 175, in load
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'kiritan_singing_extra/full_dtw/01.lab'

**Comment by r9y9** [comment]
https://github.com/r9y9/nnsvs#installation

Looks like you don't have the latest version of nnmnkwii.

**Comment by usasho** [comment]
Thank you for your reply
I get this error even with Nnmnkwii == 0.0.20
The latest Nnmnkwii is installed

**Comment by r9y9** [comment]
Please read the installation guide.

> nnmnkwii: development version (master branch) is required

**Comment by usasho** [comment]
running install
running bdist_egg
running egg_info
writing nnmnkwii.egg-info/PKG-INFO
writing dependency_links to nnmnkwii.egg-info/dependency_links.txt
writing requirements to nnmnkwii.egg-info/requires.txt
writing top-level names to nnmnkwii.egg-info/top_level.txt
reading manifest file 'nnmnkwii.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'nnmnkwii.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
-- Building version 0.0.21
copying nnmnkwii/version.py -> build/lib.linux-x86_64-3.6/nnmnkwii
running build_ext
skipping 'nnmnkwii/util/_linalg.c' Cython extension (up-to-date)
skipping 'nnmnkwii/paramgen/mlpg_helper.c' Cython extension (up-to-date)
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/tests
copying build/lib.linux-x86_64-3.6/tests/test_postfilters.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib.linux-x86_64-3.6/tests/__init__.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib.linux-x86_64-3.6/tests/test_paramgen.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib.linux-x86_64-3.6/tests/test_util.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib.linux-x86_64-3.6/tests/test_metrics.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib.linux-x86_64-3.6/tests/test_preprocessing.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib.linux-x86_64-3.6/tests/test_datasets.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib.linux-x86_64-3.6/tests/test_pack_pad_sequence.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib.linux-x86_64-3.6/tests/test_frontend.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib.linux-x86_64-3.6/tests/test_baseline.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib.linux-x86_64-3.6/tests/test_functions.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib.linux-x86_64-3.6/tests/test_autograd.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib.linux-x86_64-3.6/tests/test_real_datasets.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib.linux-x86_64-3.6/tests/test_io.py -> build/bdist.linux-x86_64/egg/tests
creating build/bdist.linux-x86_64/egg/nnmnkwii
creating build/bdist.linux-x86_64/egg/nnmnkwii/datasets
copying build/lib.linux-x86_64-3.6/nnmnkwii/datasets/jsut.py -> build/bdist.linux-x86_64/egg/nnmnkwii/datasets
copying build/lib.linux-x86_64-3.6/nnmnkwii/datasets/__init__.py -> build/bdist.linux-x86_64/egg/nnmnkwii/datasets
copying build/lib.linux-x86_64-3.6/nnmnkwii/datasets/ljspeech.py -> build/bdist.linux-x86_64/egg/nnmnkwii/datasets
copying build/lib.linux-x86_64-3.6/nnmnkwii/datasets/vcc2016.py -> build/bdist.linux-x86_64/egg/nnmnkwii/datasets
copying build/lib.linux-x86_64-3.6/nnmnkwii/datasets/vctk.py -> build/bdist.linux-x86_64/egg/nnmnkwii/datasets
copying build/lib.linux-x86_64-3.6/nnmnkwii/datasets/cmu_arctic.py -> build/bdist.linux-x86_64/egg/nnmnkwii/datasets
copying build/lib.linux-x86_64-3.6/nnmnkwii/datasets/jvs.py -> build/bdist.linux-x86_64/egg/nnmnkwii/datasets
copying build/lib.linux-x86_64-3.6/nnmnkwii/datasets/voice_statistics.py -> build/bdist.linux-x86_64/egg/nnmnkwii/datasets
creating build/bdist.linux-x86_64/egg/nnmnkwii/paramgen
copying build/lib.linux-x86_64-3.6/nnmnkwii/paramgen/__init__.py -> build/bdist.linux-x86_64/egg/nnmnkwii/paramgen
copying build/lib.linux-x86_64-3.6/nnmnkwii/paramgen/mlpg_helper.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/nnmnkwii/paramgen
copying build/lib.linux-x86_64-3.6/nnmnkwii/paramgen/_mlpg.py -> build/bdist.linux-x86_64/egg/nnmnkwii/paramgen
creating build/bdist.linux-x86_64/egg/nnmnkwii/io
copying build/lib.linux-x86_64-3.6/nnmnkwii/io/__init__.py -> build/bdist.linux-x86_64/egg/nnmnkwii/io
copying build/lib.linux-x86_64-3.6/nnmnkwii/io/hts.py -> build/bdist.linux-x86_64/egg/nnmnkwii/io
creating build/bdist.linux-x86_64/egg/nnmnkwii/preprocessing
copying build/lib.linux-x86_64-3.6/nnmnkwii/preprocessing/f0.py -> build/bdist.linux-x86_64/egg/nnmnkwii/preprocessing
copying build/lib.linux-x86_64-3.6/nnmnkwii/preprocessing/__init__.py -> build/bdist.linux-x86_64/egg/nnmnkwii/preprocessing
copying build/lib.linux-x86_64-3.6/nnmnkwii/preprocessing/modspec.py -> build/bdist.linux-x86_64/egg/nnmnkwii/preprocessing
copying build/lib.linux-x86_64-3.6/nnmnkwii/preprocessing/generic.py -> build/bdist.linux-x86_64/egg/nnmnkwii/preprocessing
copying build/lib.linux-x86_64-3.6/nnmnkwii/preprocessing/alignment.py -> build/bdist.linux-x86_64/egg/nnmnkwii/preprocessing
copying build/lib.linux-x86_64-3.6/nnmnkwii/__init__.py -> build/bdist.linux-x86_64/egg/nnmnkwii
creating build/bdist.linux-x86_64/egg/nnmnkwii/baseline
copying build/lib.linux-x86_64-3.6/nnmnkwii/baseline/gmm.py -> build/bdist.linux-x86_64/egg/nnmnkwii/baseline
copying build/lib.linux-x86_64-3.6/nnmnkwii/baseline/__init__.py -> build/bdist.linux-x86_64/egg/nnmnkwii/baseline
copying build/lib.linux-x86_64-3.6/nnmnkwii/version.py -> build/bdist.linux-x86_64/egg/nnmnkwii
creating build/bdist.linux-x86_64/egg/nnmnkwii/functions
copying build/lib.linux-x86_64-3.6/nnmnkwii/functions/__init__.py -> build/bdist.linux-x86_64/egg/nnmnkwii/functions
creating build/bdist.linux-x86_64/egg/nnmnkwii/util
copying build/lib.linux-x86_64-3.6/nnmnkwii/util/linalg.py -> build/bdist.linux-x86_64/egg/nnmnkwii/util
copying build/lib.linux-x86_64-3.6/nnmnkwii/util/_linalg.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/nnmnkwii/util
copying build/lib.linux-x86_64-3.6/nnmnkwii/util/__init__.py -> build/bdist.linux-x86_64/egg/nnmnkwii/util
copying build/lib.linux-x86_64-3.6/nnmnkwii/util/files.py -> build/bdist.linux-x86_64/egg/nnmnkwii/util
creating build/bdist.linux-x86_64/egg/nnmnkwii/util/_example_data
copying build/lib.linux-x86_64-3.6/nnmnkwii/util/_example_data/arctic_a0009.wav -> build/bdist.linux-x86_64/egg/nnmnkwii/util/_example_data
copying build/lib.linux-x86_64-3.6/nnmnkwii/util/_example_data/questions-radio_dnn_416.hed -> build/bdist.linux-x86_64/egg/nnmnkwii/util/_example_data
copying build/lib.linux-x86_64-3.6/nnmnkwii/util/_example_data/arctic_a0009_phone.lab -> build/bdist.linux-x86_64/egg/nnmnkwii/util/_example_data
creating build/bdist.linux-x86_64/egg/nnmnkwii/util/_example_data/slt_arctic_demo_data
creating build/bdist.linux-x86_64/egg/nnmnkwii/util/_example_data/slt_arctic_demo_data/Y_acoustic
copying build/lib.linux-x86_64-3.6/nnmnkwii/util/_example_data/slt_arctic_demo_data/Y_acoustic/arctic_a0002.npz -> build/bdist.linux-x86_64/egg/nnmnkwii/util/_example_data/slt_arctic_demo_data/Y_acoustic
copying build/lib.linux-x86_64-3.6/nnmnkwii/util/_example_data/slt_arctic_demo_data/Y_acoustic/arctic_a0003.npz -> build/bdist.linux-x86_64/egg/nnmnkwii/util/_example_data/slt_arctic_demo_data/Y_acoustic
copying build/lib.linux-x86_64-3.6/nnmnkwii/util/_example_data/slt_arctic_demo_data/Y_acoustic/arctic_a0001.npz -> build/bdist.linux-x86_64/egg/nnmnkwii/util/_example_data/slt_arctic_demo_data/Y_acoustic
creating build/bdist.linux-x86_64/egg/nnmnkwii/util/_example_data/slt_arctic_demo_data/X_acoustic
copying build/lib.linux-x86_64-3.6/nnmnkwii/util/_example_data/slt_arctic_demo_data/X_acoustic/arctic_a0002.npz -> build/bdist.linux-x86_64/egg/nnmnkwii/util/_example_data/slt_arctic_demo_data/X_acoustic
copying build/lib.linux-x86_64-3.6/nnmnkwii/util/_example_data/slt_arctic_demo_data/X_acoustic/arctic_a0003.npz -> build/bdist.linux-x86_64/egg/nnmnkwii/util/_example_data/slt_arctic_demo_data/X_acoustic
copying build/lib.linux-x86_64-3.6/nnmnkwii/util/_example_data/slt_arctic_demo_data/X_acoustic/arctic_a0001.npz -> build/bdist.linux-x86_64/egg/nnmnkwii/util/_example_data/slt_arctic_demo_data/X_acoustic
creating build/bdist.linux-x86_64/egg/nnmnkwii/util/_example_data/slt_arctic_demo_data/Y_duration
copying build/lib.linux-x86_64-3.6/nnmnkwii/util/_example_data/slt_arctic_demo_data/Y_duration/arctic_a0002.npz -> build/bdist.linux-x86_64/egg/nnmnkwii/util/_example_data/slt_arctic_demo_data/Y_duration
copying build/lib.linux-x86_64-3.6/nnmnkwii/util/_example_data/slt_arctic_demo_data/Y_duration/arctic_a0003.npz -> build/bdist.linux-x86_64/egg/nnmnkwii/util/_example_data/slt_arctic_demo_data/Y_duration
copying build/lib.linux-x86_64-3.6/nnmnkwii/util/_example_data/slt_arctic_demo_data/Y_duration/arctic_a0001.npz -> build/bdist.linux-x86_64/egg/nnmnkwii/util/_example_data/slt_arctic_demo_data/Y_duration
creating build/bdist.linux-x86_64/egg/nnmnkwii/util/_example_data/slt_arctic_demo_data/X_duration
copying build/lib.linux-x86_64-3.6/nnmnkwii/util/_example_data/slt_arctic_demo_data/X_duration/arctic_a0002.npz -> build/bdist.linux-x86_64/egg/nnmnkwii/util/_example_data/slt_arctic_demo_data/X_duration
copying build/lib.linux-x86_64-3.6/nnmnkwii/util/_example_data/slt_arctic_demo_data/X_duration/arctic_a0003.npz -> build/bdist.linux-x86_64/egg/nnmnkwii/util/_example_data/slt_arctic_demo_data/X_duration
copying build/lib.linux-x86_64-3.6/nnmnkwii/util/_example_data/slt_arctic_demo_data/X_duration/arctic_a0001.npz -> build/bdist.linux-x86_64/egg/nnmnkwii/util/_example_data/slt_arctic_demo_data/X_duration
copying build/lib.linux-x86_64-3.6/nnmnkwii/util/_example_data/COPYING -> build/bdist.linux-x86_64/egg/nnmnkwii/util/_example_data
copying build/lib.linux-x86_64-3.6/nnmnkwii/util/_example_data/arctic_a0009_state.lab -> build/bdist.linux-x86_64/egg/nnmnkwii/util/_example_data
creating build/bdist.linux-x86_64/egg/nnmnkwii/autograd
creating build/bdist.linux-x86_64/egg/nnmnkwii/autograd/_impl
copying build/lib.linux-x86_64-3.6/nnmnkwii/autograd/_impl/__init__.py -> build/bdist.linux-x86_64/egg/nnmnkwii/autograd/_impl
copying build/lib.linux-x86_64-3.6/nnmnkwii/autograd/_impl/modspec.py -> build/bdist.linux-x86_64/egg/nnmnkwii/autograd/_impl
copying build/lib.linux-x86_64-3.6/nnmnkwii/autograd/_impl/mlpg.py -> build/bdist.linux-x86_64/egg/nnmnkwii/autograd/_impl
copying build/lib.linux-x86_64-3.6/nnmnkwii/autograd/__init__.py -> build/bdist.linux-x86_64/egg/nnmnkwii/autograd
creating build/bdist.linux-x86_64/egg/nnmnkwii/postfilters
copying build/lib.linux-x86_64-3.6/nnmnkwii/postfilters/__init__.py -> build/bdist.linux-x86_64/egg/nnmnkwii/postfilters
creating build/bdist.linux-x86_64/egg/nnmnkwii/metrics
copying build/lib.linux-x86_64-3.6/nnmnkwii/metrics/__init__.py -> build/bdist.linux-x86_64/egg/nnmnkwii/metrics
creating build/bdist.linux-x86_64/egg/nnmnkwii/frontend
copying build/lib.linux-x86_64-3.6/nnmnkwii/frontend/merlin.py -> build/bdist.linux-x86_64/egg/nnmnkwii/frontend
copying build/lib.linux-x86_64-3.6/nnmnkwii/frontend/__init__.py -> build/bdist.linux-x86_64/egg/nnmnkwii/frontend
creating build/bdist.linux-x86_64/egg/nnmnkwii/display
copying build/lib.linux-x86_64-3.6/nnmnkwii/display/__init__.py -> build/bdist.linux-x86_64/egg/nnmnkwii/display
byte-compiling build/bdist.linux-x86_64/egg/tests/test_postfilters.py to test_postfilters.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/test_paramgen.py to test_paramgen.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/test_util.py to test_util.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/test_metrics.py to test_metrics.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/test_preprocessing.py to test_preprocessing.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/test_datasets.py to test_datasets.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/test_pack_pad_sequence.py to test_pack_pad_sequence.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/test_frontend.py to test_frontend.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/test_baseline.py to test_baseline.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/test_functions.py to test_functions.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/test_autograd.py to test_autograd.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/test_real_datasets.py to test_real_datasets.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/test_io.py to test_io.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/datasets/jsut.py to jsut.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/datasets/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/datasets/ljspeech.py to ljspeech.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/datasets/vcc2016.py to vcc2016.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/datasets/vctk.py to vctk.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/datasets/cmu_arctic.py to cmu_arctic.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/datasets/jvs.py to jvs.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/datasets/voice_statistics.py to voice_statistics.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/paramgen/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/paramgen/_mlpg.py to _mlpg.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/io/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/io/hts.py to hts.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/preprocessing/f0.py to f0.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/preprocessing/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/preprocessing/modspec.py to modspec.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/preprocessing/generic.py to generic.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/preprocessing/alignment.py to alignment.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/baseline/gmm.py to gmm.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/baseline/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/version.py to version.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/functions/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/util/linalg.py to linalg.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/util/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/util/files.py to files.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/autograd/_impl/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/autograd/_impl/modspec.py to modspec.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/autograd/_impl/mlpg.py to mlpg.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/autograd/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/postfilters/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/metrics/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/frontend/merlin.py to merlin.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/frontend/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/display/__init__.py to __init__.cpython-36.pyc
creating stub loader for nnmnkwii/util/_linalg.cpython-36m-x86_64-linux-gnu.so
creating stub loader for nnmnkwii/paramgen/mlpg_helper.cpython-36m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/util/_linalg.py to _linalg.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/nnmnkwii/paramgen/mlpg_helper.py to mlpg_helper.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying nnmnkwii.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying nnmnkwii.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying nnmnkwii.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying nnmnkwii.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying nnmnkwii.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
nnmnkwii.paramgen.__pycache__.mlpg_helper.cpython-36: module references __file__
nnmnkwii.util.__pycache__._linalg.cpython-36: module references __file__
tests.__pycache__.test_baseline.cpython-36: module references __file__
tests.__pycache__.test_datasets.cpython-36: module references __file__
tests.__pycache__.test_frontend.cpython-36: module references __file__
tests.__pycache__.test_io.cpython-36: module references __file__
tests.__pycache__.test_pack_pad_sequence.cpython-36: module references __file__
tests.__pycache__.test_postfilters.cpython-36: module references __file__
creating 'dist/nnmnkwii-0.0.21-py3.6-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing nnmnkwii-0.0.21-py3.6-linux-x86_64.egg
removing '/usr/local/lib/python3.6/dist-packages/nnmnkwii-0.0.21-py3.6-linux-x86_64.egg' (and everything under it)
creating /usr/local/lib/python3.6/dist-packages/nnmnkwii-0.0.21-py3.6-linux-x86_64.egg
Extracting nnmnkwii-0.0.21-py3.6-linux-x86_64.egg to /usr/local/lib/python3.6/dist-packages
nnmnkwii 0.0.21 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.6/dist-packages/nnmnkwii-0.0.21-py3.6-linux-x86_64.egg
Processing dependencies for nnmnkwii==0.0.21
Searching for bandmat==0.7
Best match: bandmat 0.7
Adding bandmat 0.7 to easy-install.pth file

Using /usr/local/lib/python3.6/dist-packages
Searching for tqdm==4.43.0
Best match: tqdm 4.43.0
Adding tqdm 4.43.0 to easy-install.pth file
Installing tqdm script to /usr/local/bin

Using /usr/local/lib/python3.6/dist-packages
Searching for pysptk==0.1.17
Best match: pysptk 0.1.17
Adding pysptk 0.1.17 to easy-install.pth file

Using /usr/local/lib/python3.6/dist-packages
Searching for sklearn==0.0
Best match: sklearn 0.0
Adding sklearn 0.0 to easy-install.pth file

Using /usr/local/lib/python3.6/dist-packages
Searching for fastdtw==0.3.4
Best match: fastdtw 0.3.4
Adding fastdtw 0.3.4 to easy-install.pth file

Using /usr/local/lib/python3.6/dist-packages
Searching for Cython==0.29.15
Best match: Cython 0.29.15
Adding Cython 0.29.15 to easy-install.pth file
Installing cygdb script to /usr/local/bin
Installing cython script to /usr/local/bin
Installing cythonize script to /usr/local/bin

Using /usr/local/lib/python3.6/dist-packages
Searching for scipy==1.4.1
Best match: scipy 1.4.1
Adding scipy 1.4.1 to easy-install.pth file

Using /usr/local/lib/python3.6/dist-packages
Searching for numpy==1.18.2
Best match: numpy 1.18.2
Adding numpy 1.18.2 to easy-install.pth file
Installing f2py script to /usr/local/bin
Installing f2py3 script to /usr/local/bin
Installing f2py3.6 script to /usr/local/bin

Using /usr/local/lib/python3.6/dist-packages
Searching for decorator==4.4.2
Best match: decorator 4.4.2
Adding decorator 4.4.2 to easy-install.pth file

Using /home/scss/.local/lib/python3.6/site-packages
Searching for six==1.14.0
Best match: six 1.14.0
Adding six 1.14.0 to easy-install.pth file

Using /home/scss/.local/lib/python3.6/site-packages
Searching for scikit-learn==0.22.1
Best match: scikit-learn 0.22.1
Adding scikit-learn 0.22.1 to easy-install.pth file

Using /usr/local/lib/python3.6/dist-packages
Searching for joblib==0.14.1
Best match: joblib 0.14.1
Adding joblib 0.14.1 to easy-install.pth file

Using /usr/local/lib/python3.6/dist-packages
Finished processing dependencies for nnmnkwii==0.0.21
 
I installed the master branch, but I get the same error
Leave a log
