### ISSUE TITLE
How do I train NNSVS?

### ISSUE THREAD

**Issue by firelex** [r9y9/nnsvs#40]
Could you add instructions for how to train NNSVS on a new data set?  I have 50 English language wav/lab files and would like to train the model afresh.

**Comment by r9y9** [comment]
I am currently working on other priority items (e.g. #15) so I cannot guarantee how soon I will work on preparing the instructions. In the meantime, please check the thread https://github.com/r9y9/nnsvs/issues/22#issuecomment-703466270.

**Comment by taroushirani** [comment]
Hello, firelex. To add to my previous comments in #22, NNSVS makes use of sinsy[1] via pysinsy[2] to convert musicxml files to HTS full-context label files, and currently it supports Japanese only.  I have the forked version of sinsy[3] which supports English and Chinese(Chinese support is imported from Sinsy-Remix[4]), but I have not fully tested it yet.  If you are interested, please see my forked version of sinsy.

1. http://www.sinsy.jp/
2. https://github.com/r9y9/pysinsy
3. https://github.com/taroushirani/sinsy/tree/m17n_dev
4. https://github.com/hyperzlib/Sinsy-Remix

**Comment by firelex** [comment]
Super, very helpful.  I'll give this a try.  I've used Gentle for forced alignment so far, will evaluate it against the sinsy fork!
