### ISSUE TITLE
Flipping the wrong dimension in TimeInvFIRFilter

### ISSUE THREAD

**Issue by naifrec** [r9y9/nnsvs#45]
Hello,

I was reading your `dsp.py` code yesterday, and came across [a small bug at line 33](
https://github.com/r9y9/nnsvs/blob/7758a716ec32a90cde74620af70ce252ef632bde/nnsvs/dsp.py#L33):

```python
self.weight.data[:, :, :] = filt_coef.flip(0)
```

The `flip` should be performed on the last dimension:

```python
self.weight.data[:, :, :] = filt_coef.flip(-1)
```

As the shape of weight is `(1, 1, kernel_size)`.

The same bug is repeated in the trainable variant `TrTimeInvFIRFilter`, but is consequence-less since you randomly initialize these weights anyway (flipping or not does not change anything).

I wanted to take this occasion to thank you from the bottom of my heart for all the code you share online, you truly are a god of open-source neural speech synthesis.

Cheers,
Guillaume

**Comment by r9y9** [comment]
Hi, I am sorry for the late reply. And thank you for your kind words. I am glad if my open-source work has helped the speech processing community.

As for the TimeInvFIRFilter: yes, it could be a bug if the filt_coef a three-dimensional array. Note that it is assumed to be a 1-D array, so it should be okay to flip the array as `flit_coef.flip(0)`.  https://github.com/r9y9/nnsvs/blob/7758a716ec32a90cde74620af70ce252ef632bde/nnsvs/dsp.py#L58

I will fix it according to your suggestion to avoid confusion. Thank you for pointing this out!

**Comment by r9y9** [comment]
Fixed https://github.com/r9y9/nnsvs/pull/46
