### ISSUE TITLE
Sample script to draw graphs of learning curves from output logs

### ISSUE THREAD

**Issue by taroushirani** [r9y9/nnsvs#56]
Hello, I wrote a simple script to draw learning curves from NNSVS output logs.

https://gist.github.com/taroushirani/08683b4a7357f79713976fa66d61857c

If it is worthy for someone, I want to submit PR but I have no idea where to put this in the repository. Could anyone advise me?

**Comment by r9y9** [comment]
Hi, sorry for the late reply. How about putting it into https://github.com/r9y9/nnsvs/tree/master/utils? I would be grateful if you can make a PR!
