### ISSUE TITLE
How do I create a customized hed file?

### ISSUE THREAD

**Issue by Cardroid** [r9y9/nnsvs#63]
I checked the links below.
http://hts.sp.nitech.ac.jp
https://github.com/r9y9/sinsy
https://github.com/r9y9/nnmnkwii
https://github.com/DynamiVox/nnsvs-english-support

but I couldn't figure out the specific way.

I'm going to create a hed file for another language.
If possible, could you tell me how to write specific things such as grammar?

Thank you for the good project.

**Comment by r9y9** [comment]
I have no experience creating a hed file from scratch (I'm just following the sinsy's full-context format). Maybe better to ask people who are already working on another language support?

**Comment by Cardroid** [comment]
Thank you very much for your answer.

I found these document after a little more research.
I hope it will help others with the same problem.
https://wiki.inf.ed.ac.uk/twiki/pub/CSTR/F0parametrisation/hts_lab_format.pdf
