### ISSUE TITLE
Loss function of acoustic model goes to nan with nit-song070 data-set on Google Colaboratory

### ISSUE THREAD

**Issue by taroushirani** [r9y9/nnsvs#7]
When I try to use NNSVS with NIT-SONG070 data-set on Google Colaboratory, I get RuntimeWarning from NumPy on Stage 1(acoustic feature generation). On stage 4, loss function of acoustic model goes to nan and fail to train acoustic model.

When I disable use_harvest feature in nnsvs/bin/conf/prepare_features/config.yaml[1], NNSVS seems to work fine(and there is a minor bug in nnsvs/data/data_source.py).

I uploaded the failed ipynb to gist.github.com[2] so please see it for detail.

1. https://gist.github.com/taroushirani/dbcd4a69bc6372e173854846918c9906
2. https://gist.github.com/taroushirani/ed14e3e0228f52f4eecac68402bf34b8

**Comment by r9y9** [comment]
https://github.com/mmorise/World/pull/100 There were two memory issues in Harvest C++ implementation. I submitted a PR to WORLD and hope it will fix the issue.

**Comment by taroushirani** [comment]
Thank you for your rapid response. I built pyworld with World-cmake/harvest-memory-fixes and confirmed the problem is solved.  I hope this patch is merged into upstream.

**Comment by r9y9** [comment]
Glad to know it worked! I’ll make a PR for pyworld after my fixes get merged to upstream.

**Comment by r9y9** [comment]
The new pyworld v0.2.10 has been released and this should be solved by the new verison. Please reopn if the problem persists.
