### ISSUE TITLE
Duration modeling considering variances

### ISSUE THREAD

**Issue by r9y9** [r9y9/nnsvs#80]
Ref: http://www.apsipa.org/proceedings/2018/pdfs/0001003.pdf

![スクリーンショット 2022-03-11 20 44 26](https://user-images.githubusercontent.com/1220272/157860828-e0943d36-635a-47b0-b64b-7cee131e8214.png)

**Comment by r9y9** [comment]
@taroushirani I apologize if you are already working on this. It was easier to implement than I originally thought, so I did while working on #76. Could you check the commit https://github.com/r9y9/nnsvs/commit/62d633dac20c0e1e7adb346ea1fc83685a45727d if the implementation looks correct?

**Comment by taroushirani** [comment]
Hello, In the latest paper of sinsy[1], timelag-adjusted note length are calculated as  follows:

![duration_paper](https://user-images.githubusercontent.com/64184225/158019539-82dea8d1-723d-455e-95de-2bcfb7a2f225.png)

1. https://arxiv.org/pdf/2108.02776.pdf

https://github.com/r9y9/nnsvs/blob/8e5a96967095d56e38f840cc828f506f3b3ea787/nnsvs/gen.py#L195-L201

I'm afraid that "L_hat = L - (lag[i - 1] - lag[i]) / 50000" is correct.

**Comment by r9y9** [comment]
Ah yes, you are right. Will fix it soon.

**Comment by r9y9** [comment]
Fixed https://github.com/r9y9/nnsvs/pull/81/commits/5a5d0ca57d825a3460fe7e142590199d09b52a73

**Comment by taroushirani** [comment]
I found that when L_hat is smaller than mu.sum() (there may be too many phonemes in a short note), rho and can be negative value and then d_norm.sum() is bigger than L_hat.  

https://github.com/r9y9/nnsvs/blob/8e5a96967095d56e38f840cc828f506f3b3ea787/nnsvs/gen.py#L230-L232

The above code may generate negative d_norm and result in nnmnkwii/io/hts.py error.

**Comment by taroushirani** [comment]
I found the another issue.  L_hat can be smaller than 1 as the result of application of timelag, and this may result in estimation error.  Checking code of L_hat may be needed.

**Comment by taroushirani** [comment]
I think it may be permissible to use the conventional method to estimate duration in a short note, because the estimation error of duration of consonants in a short note may be less obvious than that in long note.

Sample code(replace with line 228)
        if is_mdn and np.any(d_norm <= 0):
            # eq (12) (using mu as d_hat)
            d_hat = pred_durations[0][note_indices[i - 1] : note_indices[i]]
            d_norm = L_hat * d_hat / d_hat.sum()

**Comment by r9y9** [comment]
Thank you very much for your comments.

> I found that when L_hat is smaller than mu.sum() (there may be too many phonemes in a short note), rho and d_norm can be negative value and then d_norm.sum() is bigger than L_hat because d_norm will be corrected as 1.

I think negative rho would be okay as it just makes phoneme durations shorter, but negative d_norm is not expected behavior and we need to fix it.

> I found the another issue. L_hat can be smaller than 1 as the result of application of timelag, and this may result in estimation error. Checking code of L_hat may be needed.


This means... our time-lag model is not well trained T.T

> I think it may be permissible to use the conventional method to estimate duration in a short note, because the estimation error of duration of consonants in a short note may be less obvious than that in long note.

If I understand correctly, negative d_norm could happen even if we use the conventional uniform duration scaling. Do you think uniform scaling is better than variance-dependent scaling? Do you observe improvements?

To prevent negative phoneme duration, I wonder if we should set a minimum duration for each phoneme. I'm thinking about:
- As is: set minimum duration to 1 for all phonemes https://github.com/r9y9/nnsvs/blob/19acb79bd355f515016528be00d7c954a8b12783/nnsvs/gen.py#L218
- To be: set minimum duration for each phoneme

Perhaps similar to https://twitter.com/canon_73/status/1451517876247007239?

**Comment by taroushirani** [comment]
> If I understand correctly, negative d_norm could happen even if we use the conventional uniform duration scaling. Do you think  uniform scaling is better than variance-dependent scaling? Do you observe improvements?

I think the conventional uniform duration scailing would not generate negative d_norm because d_hat(=mu) >0, d_hat.sum() > 0, L_hat > 0.  And it's merely the division by propotion, d_norm.sum() is always equal to L_hat and the adjustment of line 232 may never be executed.

I think that setting minimum duration uniformally or respectively may work well if we remove the  codes for adjustment at line 230-232.

**Comment by r9y9** [comment]
I think I see your point. I thought L_hat could be negative `L_hat = L - (lag[i - 1] - lag[i]) / 50000` depending on the estimated time-lags but that's a different issue and rarely happens.

**Comment by r9y9** [comment]
If I understand right, https://github.com/r9y9/nnsvs/pull/81/commits/ad6900f27f92e73534d318399a3373499e800706 and https://github.com/r9y9/nnsvs/pull/81/commits/11ad72bbf504f0a68557be308e5e7a541a7ca61d address your concern. Are the changes look right?
