### ISSUE TITLE
numpy.linalg.LinAlgError: 75-th leading minor not positive definite

### ISSUE THREAD

**Issue by stakira** [r9y9/nnsvs#94]
Stack trace:
```
Traceback (most recent call last):
  File "_\ENUNU-0.3.1\.\enunu-openutau.py", line 248, in <module>
    acoustic(sys.argv[2])
  File "_\ENUNU-0.3.1\.\enunu-openutau.py", line 208, in acoustic
    enulib.acoustic.timing2acoustic(
  File "_\ENUNU-0.3.1\.\enulib\acoustic.py", line 107, in timing2acoustic
    acoustic_features = predict_acoustic(
  File "_\ENUNU-0.3.1\python-3.8.10-embed-amd64\lib\site-packages\nnsvs\gen.py", line 282, in predict_acoustic
    pred_acoustic = multi_stream_mlpg(max_mu, max_sigma_sq, get_windows(acoustic_config.num_windows),
  File "_\ENUNU-0.3.1\python-3.8.10-embed-amd64\lib\site-packages\nnsvs\multistream.py", line 120, in multi_stream_mlpg
    y = paramgen.mlpg(x, var_, windows) if v else x
  File "_\ENUNU-0.3.1\python-3.8.10-embed-amd64\lib\site-packages\nnmnkwii\paramgen\_mlpg.py", line 200, in mlpg
    y[:, d] = bla.solveh(P, b)
  File "nnmnkwii/paramgen/_bandmat/linalg.pyx", line 302, in nnmnkwii.paramgen._bandmat.linalg.solveh
  File "nnmnkwii/paramgen/_bandmat/linalg.pyx", line 224, in nnmnkwii.paramgen._bandmat.linalg.cholesky
  File "nnmnkwii/paramgen/_bandmat/linalg.pyx", line 80, in nnmnkwii.paramgen._bandmat.linalg._cholesky_banded
numpy.linalg.LinAlgError: 75-th leading minor not positive definite
```
Note that this is nnsvs packed with ENUNU 0.3.1. It seem to have minor difference from Github tag 0.0.1.

Before denormalization
```
max_mu: torch.Size([1, 365, 199])
max_sigma: torch.Size([1, 365, 199])
```
After denormalization
```
max_mu: (365, 199)
max_sigma_sq: (365, 199)
acoustic_config.num_windows: 3
acoustic_config.stream_sizes: [180, 3, 1, 15]
acoustic_config.has_dynamic_features: [True, True, False, True]
```
Features are attached: [features.zip](https://github.com/r9y9/nnsvs/files/8394445/features.zip)

**Comment by taroushirani** [comment]
Hello, I have been consulted the same problem (https://pbs.twimg.com/media/FREU_d4UUAAxcxV?format=png&name=360x360).  I'm not familiar with mathematics, but this problem seems to result from the inappropriate matrix(not positive-definite matrix) returned from build_poe in nnmnkwii/paramgen/_mlpg.py. 

````
        b, P = build_poe(bs, precisions, win_mats)
        try:
                y[:, d] = bla.solveh(P, b)
        except numpy.linalg.LinAlgError:
                y[:, d] = bla.solve(P, b)

In my understanding, bandmat.linalg.solve is slower than solveh but has a looser restriction, right?

**Comment by r9y9** [comment]
Hi, thanks for looking into it. Your suggestion sounds reasonable. 

Also, I highly suspect that this is a numerical stability issue that can be addressed differently. Looking into the attached features, I found that the generated variance contains a very small value.

```py
> sigma = np.load("path/to/features/max_sigma_sq.npy")
> sigma.min(), sigma.max()
> (1.3833172716339162e-18, 142.80620706633766)
```

By clipping the sigma by `np.clip(sigma, 1e-17, sigma.max())`, MLPG works good for me. We can clip sigma by a larger value like `1e-14` or similar.

Could you check if it works okay for you?

**Comment by taroushirani** [comment]
Thank you for your rapid response. I don't have the data which causes this error, but Mr. Minato(@M_C3O2) have checked this problem and clipping sigma seems to work ok[1].

1. https://twitter.com/M_C3O2/status/1518527034246692865 (written in Japanese)

**Comment by stakira** [comment]
`np.maxinum(max_sigma_sq, 1e-14)` seem to be working fine, not sure how low it goes.

**Comment by r9y9** [comment]
Pushed a fix to master. Please feel free to reopen if the problem persists.
